version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking AWS CLI version...
      - aws --version
      - echo Verifying IAM role...
      - aws sts get-caller-identity
      - echo Getting ECR login password...
      - aws ecr get-login-password --region us-east-1 > password.txt
      - cat password.txt | docker login --username AWS --password-stdin 463470969380.dkr.ecr.us-east-1.amazonaws.com/github-codebuilder

  install:
    runtime-versions:
      docker: 18
  
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodejs .
      - docker tag nodejs:latest 463470969380.dkr.ecr.us-east-1.amazonaws.com/github-codebuilder:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 463470969380.dkr.ecr.us-east-1.amazonaws.com/github-codebuilder:latest
artifacts:
  files: []

